import { TIPOS_USUARIO } from "./tiposUsuario";
import { PERMISOS } from "./permisos";

export const PERMISOS_POR_TIPO_USUARIO = {
  [TIPOS_USUARIO.ADMINISTRADOR]: Object.values(PERMISOS),

  [TIPOS_USUARIO.SUPERVISOR]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RANCHOS,
    PERMISOS.VER_CULTIVOS,
    PERMISOS.VER_PERSONAL,
    PERMISOS.VER_ACTIVIDADES,
    PERMISOS.CREAR_ACTIVIDADES,
    PERMISOS.ASIGNAR_ACTIVIDADES,
    PERMISOS.VER_COSECHA,
    PERMISOS.VER_REPORTES,
  ],

  [TIPOS_USUARIO.PERSONAL_OPERATIVO]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_ACTIVIDADES,
    PERMISOS.COMPLETAR_ACTIVIDADES,
    PERMISOS.VER_COSECHA,
  ],

  [TIPOS_USUARIO.CEO]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RANCHOS,
    PERMISOS.VER_CULTIVOS,
    PERMISOS.VER_COSECHA,
    PERMISOS.VER_COSTOS,
    PERMISOS.VER_REPORTES,
  ],
};