import { ROLES } from "./roles";
import { PERMISOS } from "./permisos";

export const PERMISOS_POR_ROL = {
  [ROLES.RECURSOS_HUMANOS]: [
    PERMISOS.VER_PERSONAL,
    PERMISOS.GESTIONAR_PERSONAL,
  ],

  [ROLES.INVENTARIO]: [
    PERMISOS.VER_INVENTARIO,
    PERMISOS.GESTIONAR_INVENTARIO,
  ],

  [ROLES.RIEGO_NUTRICION]: [
    PERMISOS.VER_RIEGO,
    PERMISOS.GESTIONAR_RIEGO,
  ],

  [ROLES.SANIDAD_VEGETAL]: [
    PERMISOS.VER_SANIDAD,
    PERMISOS.GESTIONAR_SANIDAD,
  ],

  [ROLES.COSECHA_CALIDAD]: [
    PERMISOS.VER_COSECHA,
    PERMISOS.GESTIONAR_COSECHA,
  ],

  [ROLES.ADMINISTRATIVO_FINANCIERO]: [
    PERMISOS.VER_COSTOS,
    PERMISOS.GESTIONAR_COSTOS,
    PERMISOS.VER_REPORTES,
    PERMISOS.EXPORTAR_REPORTES,
  ],

  [ROLES.AUDITOR]: [
    PERMISOS.VER_DASHBOARD,
    PERMISOS.VER_RANCHOS,
    PERMISOS.VER_CULTIVOS,
    PERMISOS.VER_PERSONAL,
    PERMISOS.VER_ACTIVIDADES,
    PERMISOS.VER_DISPOSITIVOS,
    PERMISOS.VER_INVENTARIO,
    PERMISOS.VER_RIEGO,
    PERMISOS.VER_SANIDAD,
    PERMISOS.VER_COSECHA,
    PERMISOS.VER_COSTOS,
    PERMISOS.VER_REPORTES,
    PERMISOS.VER_BITACORA,
  ],
};