export const ROLES = {
  RECURSOS_HUMANOS: "RECURSOS_HUMANOS",
  INVENTARIO: "INVENTARIO",
  RIEGO_NUTRICION: "RIEGO_NUTRICION",
  SANIDAD_VEGETAL: "SANIDAD_VEGETAL",
  COSECHA_CALIDAD: "COSECHA_CALIDAD",
  ADMINISTRATIVO_FINANCIERO: "ADMINISTRATIVO_FINANCIERO",
  AUDITOR: "AUDITOR",
};